services:
  - type: web
    name: helios-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn helios.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: helios.settings
