# Generated by Django 5.0.14 on 2025-06-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_choice',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
