# Generated by Django 5.0.14 on 2025-06-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_userbookprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_quiz',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
