# Generated by Django 5.0.14 on 2025-06-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_has_quiz_book_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookprogress',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
